### ISSUE TITLE
Accept should be public function of the Contract 

### ISSUE THREAD

**Issue by bluesign** [onflow/nft-storefront#11]
I think `accept` should be a member of the Contract, and should take the saleOfferResourceID and the address as additional parameters. 

that way if everyone will have single storefront:

- it forces a single instance of StoreFront on Path set by contract (also I think we can check path when listing, and not list if it is not on the correct public path, prevents ghost offers) 
- we can clean up sale offers after they are accepted. (no need for cleanup also accepted field will not be necessary)
- we can emit events on the hostile sellers. (remove listings on the first failed attempt when NFT is not listed anymore ( OfferGoneAway(saleOfferResourceID) ) or cannot reach StoreFront (such as StoreGoneAway(address) )

Those events will be useful, if there will be some dapps showing listing etc, so they can remove users or listings from their DBs

**Comment by CineTek** [comment]
Isn't that always going to be an issue in the way NFTs work on Flow? Any project derived from standard NFT can be sold on a Third-Party marketplace as long as the actual NFT is not "locked" inside the contract or any of their "saleOffer" resources directly...? So e.g. someone has a listing on CM marketplace and on VIV3 - one of the two - in the current design - will run into an issue if sold on one of them. (not an issue for CM right now due to current wallet garden design)
I believe therefore a marketplace needs to figure out a solution that works for all use-cases and I don't believe it is therefore required in this contract 🤔

**Comment by bluesign** [comment]
@CineTek Problem is mainly ghost listing, if you have on viv3 some legendary item for 1 FLOW, if someone tries to buy it, and fails, the contract has to clean this listing normally, and emit an event. But currently to cleanup, you need to call a method, and you can only clean up sold items.

**Comment by CineTek** [comment]
Yeah sorry I deleted my comment, I misread the situation in the contract😬
